model_id: train
checkpoints: ./checkpoints_STPGeo/
root_path: ./dataset/traffic/
data_path: TJP
data: custom
features: M
freq: 0
target: OT
embed: timeF
percent: 10
seq_len: 80
pred_len: 120
label_len: 120
decay_fac: 0.75
learning_rate: 0.0001
batch_size: 128
num_workers: 10
train_epochs: 300
lradj: type1
patience: 10
gpt_layers: 3
is_gpt: 1
e_layers: 3
d_model: 768
n_heads: 16
d_ff: 512
dropout: 0.2
enc_in: 2
c_out: 2
patch_size: 16
stride: 8
kernel_size: 25
prompt_len: 256
grid_size: 64
sigmaX: 5
sigmaY: 5
loss_func: mse
pretrain: 1
freeze: 1
model: GPT4STP
max_len: -1
hid_dim: 16
tmax: 10
itr: 1
cos: 0
load_dataset: True
geohash_size: 40